server:
  port: 8010

spring:
  application:
    name: user-center

  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    hikari:
      username: root
      password: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8850
        cluster-name: Canada