server:
  port: 8040
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        group: DEFAULT_GROUP
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Add your routes here.
        - id: contents_route
          uri: lb://content-center
          predicates:
            - Path=/content/**
          filters:
            - StripPrefix=1
        - id: users_route
          uri: lb://user-center
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@hostAddrKeyResolver}"
                redis-rate-limiter.replenishRate: 10 # 令牌桶填充的速率 秒为单位
                redis-rate-limiter.burstCapacity: 10 # 令牌桶总容量
                redis-rate-limiter.requestedTokens: 1 # 每次请求获取的令牌数
        - id: order_route
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
    sentinel:
      eager: true
      transport:
        dashboard: http://localhost:8080
  redis:
    host: 127.0.0.1
    port: 6379
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

ken:
  gateway:
    api:
      groupsMap:
        MRPlus: 0.6
        SA: 0.2
        other: 0.2
      totalPermitsPerSecond: 10
      tokenName: JWT-TOKEN
